### ISSUE TITLE
Create a query specific to pulling back the labels from an issue that generated a particular PR

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/iqss_gh_reporting#26]
The issue should take a PR number and repo and return the basic information for the issue that is closed by this PR if it exists.
The data needs to be returned in JSON format.  The query must be stored in such a way that variants on the theme can be easily run using the same basic code.

This issue supports:
- https://github.com/thisaintwork/iqss_gh_reporting/issues/12

**Comment by mikeaintworkin** [comment]
Left off editing:

graphql_query_lib.py
The query string thus far is:
```
    query ($loginOrg: String!, $repo: String!, $firstFew: Int, $startWith: String) {
        repository(followRenames:false, owner: $loginOrg, name: $repo) {
                pullRequest (number: $number) {
                    closingIssuesReferences(first: 100) {
                        totalCount
                        pageInfo {
                            hasNextPage
                            hasPreviousPage
                            endCursor
                            startCursor
                        }
                        nodes {
                            ...issueFields
                        }

                    }
                }
        }
    }
```

It looks like I have access to all the fields for each of the list of issues that could be associated with a PR. This means just one call per PR.  The chance of having more than let's say 5 associated issues is like None so I won't have to paginate. 

This means that given the PR number and the repo, I should be able to retrieve the issue that may close this PR. I'll have to arbitrarily? choose the one to use.  I only need the issue numbers, as I will need to look those up in the data from the start of the sprint to get the size of that issue at the start of the sprint.

Thinking about this... If there are more than one issue associated with this PR and those issues are off the board because of this PR then the points are cumulative.


Next steps:
- finish the query. 

- Setup framework_03.py to test this with fetch_from_repository.py
-

**Comment by mikeaintworkin** [comment]
Framework-03 basename is taken so I'm going to use framework-04 as the basename for getting the most basic query working.

I had originally started framework-01.py but I had bitten off too much at once:
---
    # ================================================================================================================
    # The objective of this frame is to work through the following steps:
    # - read in a dataframe (real data)
    # - find a PR in the frame that has a zero size
    # - retrieve the closes data
    #   - Figure out what that data looks like. Is it a list? is it a string?
    # - lookup each of the issues in the list in a dataframe
    #   - successfully return the data for each of the issues
    #   - fail to look up the data for one or more of the issues.
    # - lookup each of the issues in the list in GitHub
    #   - successfully return the data for each of the issues
    #   - fail to look up the data for one or more of the issues.
    # ================================================================================================================

**Comment by mikeaintworkin** [comment]
for framework_04 here is the starting objective:
    # ================================================================================================================
    # The objective of this frame is to work through the following steps:
    # - take in a PR number and repo
    # - fetch the Issue or issues that the PR is supposed to close 
    # - fetch the Issue labels
    # ================================================================================================================

**Comment by mikeaintworkin** [comment]
I got caught up in a Linux reinstall today so nothing additional done.
One thing I did do:
- Reorganized the framework scripts that I've been using to explore new features including this one and checked them in under ./scripts/scaffolding.  I figure I can always delete these from the repository later.  They are not quite test scripts, but could become tests scripts later.

**Comment by mikeaintworkin** [comment]
incremental check-in.  I've got an example, known query working. Today I moved the functions that return the queries (graphql_query_lib) into a global dictionary.

**Comment by mikeaintworkin** [comment]
Next step:
- finish support in the framework for a specific set of directories.
- Do the specific lookup.

**Comment by mikeaintworkin** [comment]
Incremental progress today.
- I dealt with some interesting side effects from the environment clean up. Last weekend I reinstalled my Ubuntu virtual machine from scratch and brought Pycharm up. Wherever possible on this install, I've been using a virtual environment. I'm not knowledgeable about virtual environments. One of the side effects I hit today was that now that I've wherever possible install things using PIP mostly from within Pycharm into a local virtual environment, I've found that in order to invoke the code outside of the dev environment, I've needed to also invoke the virtual environment. In retrospect that totally makes sense, but it was a surprise, mostly because I am not overly familiar with what exactly is involved when a build is done. It may be that there are things that are related to the build environment that probably should be installed globally. Not sure. For now when in doubt, I'm going to install the virtual environment.
- All that said, I am now able to launch the scaffolding for working on this issue with a built in working version of the code, outside of the Pycharm environment.

Next step:
- finally to the specific lookup

**Comment by mikeaintworkin** [comment]
I keep losing the shared directory to our shared MS onedrive link. This morning I created a hard link from:
- C:\Users\mir924\OneDrive - Harvard University\iq_reporting_collab
to:
- C:\Users\mir924\iq_reporting_collab

Maybe? That will prevent the VM share from disappearing?

**Comment by mikeaintworkin** [comment]
wahoo! First good query!
```
{
    "repository": {
        "pullRequest": {
            "closingIssuesReferences": {
                "totalCount": 1,
                "pageInfo": {
                    "hasNextPage": false,
                    "hasPreviousPage": false,
                    "endCursor": "MQ",
                    "startCursor": "MQ"
                },
                "nodes": [
                    {
                        "repository": {
                            "name": "dataverse"
                        },
                        "title": "Add GENERIC storage quota check to the file upload framework. ",
                        "number": 9361,
                        "id": "I_kwDOANZmvM5denrc",
                        "url": "https://github.com/IQSS/dataverse/issues/9361",
                        "closed": false,
                        "closedAt": null,
                        "labels": {
                            "totalCount": 2,
                            "nodes": [
                                {
                                    "name": "Size: 80"
                                },
                                {
                                    "name": "D: FixRateLimitingBehaviors"
                                }
                            ]
                        }
                    }
                ]
            }
        }
    }
}
``

**Comment by mikeaintworkin** [comment]
I'm not going to address corner cases for this issue, but I do need to cover the case where there is more than one issue and where there are not issues.

**Comment by mikeaintworkin** [comment]
first:
- ask for an issue: i.e. ask for a PR that does not exist.
```
-----
kickoff the Test

================================
+ python3 framework_02.py --loginOrg IQSS --repo dataverse --output_dir /home/barry/Documents/github_reporting/framework_02/out --number 9416
Running /home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py as the main program
{'query_str': '\n    query ($loginOrg: String!, $repo: String!, $firstFew: Int!, $startWith: String, $number: Int!) {\n        repository(followRenames:false, owner: $loginOrg, name: $repo) {\n                pullRequest (number: $number) {\n                    closingIssuesReferences(first: $firstFew, after: $startWith) {\n                        totalCount\n                        pageInfo {\n                            hasNextPage\n                            hasPreviousPage\n                            endCursor\n                       startCursor\n                        }\n                        nodes {\n                            ...issueFields\n                        }\n\n                    }\n                }\n        }\n    }\n        \n    fragment issueFields on Issue {\n        repository {\n            name\n        }\n        title\n        number\n        id\n        url\n        closed\n        closedAt\n        labels (first: 100) {\n          totalCount\n            nodes {\n                name\n            }\n        }\n    }\n    ', 'has_next_page_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'hasNextPage'], 'start_with_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'endCursor'], 'query_vars': {'loginOrg': 'IQSS', 'repo': 'dataverse', 'number': '', 'firstFew': 100, 'startWith': ''}}
dataverse
Traceback (most recent call last):
File "/home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py", line 62, in <module>
main()
File "/home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py", line 57, in main
fetcher = fetch_from_repository.GraphQLFetcher(auth_token_val, query_dict)
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/iqss_gh_reporting/fetch_from_repository.py", line 37, in __init__
self._fetch_items()
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/iqss_gh_reporting/fetch_from_repository.py", line 54, in _fetch_items
data = client.execute(self._query, variable_values=self._query_input_params)
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/gql/client.py", line 388, in execute
data = loop.run_until_complete(
File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
return future.result()
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/gql/client.py", line 285, in execute_async
return await session.execute(
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/gql/client.py", line 1231, in execute
raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'type': 'NOT_FOUND', 'path': ['repository', 'pullRequest'], 'locations': [{'line': 3, 'column': 5}], 'message': 'Could not resolve to a PullRequest with the number of 9416.'}
```

**Comment by mikeaintworkin** [comment]
The objective for this is met.
I'm going to address the corner cases in separate issues.

**Comment by mikeaintworkin** [comment]
For posterity - the result

```
============================
pwd: /home/barry/PycharmProjects/iqss_gh_reporting/scripts

Build and install complete.
The build will put these files and their associated libraries in your path. 
create_iq_snapshot_init
create_iq_snapshot


Next Steps:
() Check that the build actually completed succesfully by reviewing the output.
() Test out the create_iq_snapshot_init build correctly using 

create_iq_snapshot_init --help

() Follow the rest of the instructions in the readme

============================

+ popd
~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding
+ source /home/barry/PycharmProjects/iqss_gh_reporting/venv/bin/activate
++ '[' /home/barry/PycharmProjects/iqss_gh_reporting/venv/bin/activate = ./framework_02.sh ']'
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/home/barry/PycharmProjects/iqss_gh_reporting/venv
++ '[' linux-gnu = cygwin ']'
++ '[' linux-gnu = msys ']'
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/home/barry/.local/bin:/home/barry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/barry/.local/share/JetBrains/Toolbox/scripts
++ PATH=/home/barry/PycharmProjects/iqss_gh_reporting/venv/bin:/home/barry/.local/bin:/home/barry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/barry/.local/share/JetBrains/Toolbox/scripts
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /home/barry/PycharmProjects/iqss_gh_reporting/venv
++ PS1='(venv) '
++ export PS1
++ alias pydoc
++ true
++ hash -r
+ SCRIPT_DIR=/home/barry/PycharmProjects/iqss_gh_reporting/scripts
+ WRK_DIR_RT=/home/barry/Documents/github_reporting/framework_02
+ cat

--------------------------------
Directories:
SCRIPT_DIR: "/home/barry/PycharmProjects/iqss_gh_reporting/scripts"
WRK_DIR_RT: "/home/barry/Documents/github_reporting/framework_02"
INDIR: "/home/barry/Documents/github_reporting/framework_02/in"
WRKDIR: "/home/barry/Documents/github_reporting/framework_02/wrk"
OUTDIR: "/home/barry/Documents/github_reporting/framework_02/out"

-------------------------------
input file:
/home/barry/Documents/github_reporting/framework_02/in/

+ mkdir -p /home/barry/Documents/github_reporting/framework_02/in
+ mkdir -p /home/barry/Documents/github_reporting/framework_02/wrk
+ mkdir -p /home/barry/Documents/github_reporting/framework_02/out
+ rm '/home/barry/Documents/github_reporting/framework_02/out/*'
rm: cannot remove '/home/barry/Documents/github_reporting/framework_02/out/*': No such file or directory
+ cat
++ find /home/barry/Documents/github_reporting/framework_02 -type f
--------------------------------
Directories Contents:

/home/barry/Documents/github_reporting/framework_02/out/output.json

-----
kickoff the Test

================================
+ cat
--------------------------------
PR exists and has a single issue associated with it.
9369 Shib groups (and other custom groups), as subgroups of an explicit group #9597
--------------------------------
+ python3 framework_02.py --loginOrg IQSS --repo dataverse --output_dir /home/barry/Documents/github_reporting/framework_02/out --number 9597
Running /home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py as the main program
{'query_str': '\n    query ($loginOrg: String!, $repo: String!, $firstFew: Int!, $startWith: String, $number: Int!) {\n        repository(followRenames:false, owner: $loginOrg, name: $repo) {\n                pullRequest (number: $number) {\n                    closingIssuesReferences(first: $firstFew, after: $startWith) {\n                        totalCount\n                        pageInfo {\n                            hasNextPage\n                            hasPreviousPage\n                            endCursor\n                       startCursor\n                        }\n                        nodes {\n                            ...issueFields\n                        }\n\n                    }\n                }\n        }\n    }\n        \n    fragment issueFields on Issue {\n        repository {\n            name\n        }\n        title\n        number\n        id\n        url\n        closed\n        closedAt\n        labels (first: 100) {\n          totalCount\n            nodes {\n                name\n            }\n        }\n    }\n    ', 'has_next_page_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'hasNextPage'], 'start_with_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'endCursor'], 'query_vars': {'loginOrg': 'IQSS', 'repo': 'dataverse', 'number': '', 'firstFew': 100, 'startWith': ''}}
dataverse
Saving result to file:
/home/barry/Documents/github_reporting/framework_02/out/output.json
+ exit 0
barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding$ cat /home/barry/Documents/github_reporting/framework_02/out/output.json
{
"repository": {
"pullRequest": {
"closingIssuesReferences": {
"totalCount": 1,
"pageInfo": {
"hasNextPage": false,
"hasPreviousPage": false,
"endCursor": "MQ",
"startCursor": "MQ"
},
"nodes": [
{
"repository": {
"name": "dataverse"
},
"title": "Shib group in another group doesn't work",
"number": 9369,
"id": "I_kwDOANZmvM5d4X5V",
"url": "https://github.com/IQSS/dataverse/issues/9369",
"closed": true,
"closedAt": "2023-06-05T21:19:14Z",
"labels": {
"totalCount": 1,
"nodes": [
{
"name": "Size: 3"
}
]
}
}
]
}
}
}
}barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding$
```
