### ISSUE TITLE
URL for the issue that closes a PR does not appear to be present in the legacy API call

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/iqss_gh_reporting#29]
The error was triggered directly following this test:
```
if card_type == "pull":
```

The error is referring to an "Issue" object but the error occurred in code where the card_type would have to be a pull request.
This makes me feel that there may be an init issue with card_type variable

```
start: 0 cards processed: IQSS/dataverse, Column ▶ SPRINT READY
Traceback (most recent call last):
File "/home/perftest/.local/bin/create_iq_snapshot", line 94, in <module>
main()
File "/home/perftest/.local/bin/create_iq_snapshot", line 68, in main
sprint_data.df = pdio.LegacyProjectCards(
File "/home/perftest/.local/lib/python3.10/site-packages/iqss_gh_reporting/legacy.py", line 103, in __init__
self._fetch_data()
File "/home/perftest/.local/lib/python3.10/site-packages/iqss_gh_reporting/legacy.py", line 118, in _fetch_data
if not self._get_project_cards_api_obj():
File "/home/perftest/.local/lib/python3.10/site-packages/iqss_gh_reporting/legacy.py", line 168, in _get_project_cards_api_obj
this_pr_closes=card_content.issue_url()
AttributeError: 'Issue' object has no attribute 'issue_url'
```

**Comment by mikeaintworkin** [comment]
For now I added -                
 if card_content is not None:
                    card_type = "" <<<

**Comment by mikeaintworkin** [comment]
used this loop to test the code
```
~/DevCode/github-com-mreekie/builds
bash -cl "/usr/bin/python3.10 /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/setup.py bdist_wheel"; pip install .
pushd /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/scripts
 ./workflow-May032023sprint-snapshot.sh
create_iq_snapshot
popd
```

**Comment by mikeaintworkin** [comment]
The changed logic looks like this:

```
                 if card_content is not None:
                    regex1 = re.compile(r"(/issues/|/pull/)")
                    regex2 = re.compile(r"(issues|pull)")
                    card_type = regex1.search(card_content.html_url).group(0)
                    card_type = regex2.search(card_type).group(0)
                    card_type = 'undefined' if card_type not in ['issues', 'pull'] else card_type
                    if self._card_count % 50 == 0:
                        print(f">>>>>> {self._card_count} # cards {self._project_object.name}: {column.name} \
                        ,{card_type} ,{card_content.number},{card_content.repository.name} ,{card_content.title}")

                    # If the card is associated with a pull request, include the associated issues
                    # in PyGitHub, the only thing we have to workwith is the issue_url
                    # The legacy api says that this isa list of URLs, but PyGithub returns a single URL
                    this_pr_closes = ""
                    if card_type == "pull":
                        if hasattr(card_content, 'issue_url') and card_content.issue_url is not None:
                            this_pr_closes = card_content.issue_url
                        else:
                            this_pr_closes = "undefined"
```

**Comment by mikeaintworkin** [comment]
I'm still puzzled.
Adding this code:
```
                    if card_type == "pull":
                        if hasattr(card_content, 'issue_url'):
                            this_pr_closes = this_pr_closes + ";" + "has attr issue_url"
                            if card_content.issue_url is not None:
                                this_pr_closes = card_content.issue_url
                            else:
                                this_pr_closes = this_pr_closes + ";" + "issue_url is None"
                        else:
                            this_pr_closes  = this_pr_closes + ";" + "has no attr issue_url"
```

**Comment by mikeaintworkin** [comment]
So it turns out that I'm not getting back the attribute issue_url.
upgraded to PyGithub-1.58.2 which is from May 2023 
https://pypi.org/project/PyGithub/

Looking at the docs, I'm looping through cards. each [project card](https://pygithub.readthedocs.io/en/latest/github_objects/ProjectCard.html#github.ProjectCard.ProjectCard) has a get_content() method:

Calls:	GET /repos/{owner}/{repo}/pulls/{number}
Parameters:	content_type – string, optional
Return type:	github.PullRequest.PullRequest or github.Issue.Issue

https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest  has an [issue_url](https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.issue_url)

https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue

**Comment by mikeaintworkin** [comment]
I looked at the source for the Pull request object briefly.
https://github.com/PyGithub/PyGithub/blob/master/github/PullRequest.py
There's no __init__ def so there's more going on here than I understand.
I do see references to this property in the code.
I'm going to see if I can see what is actually there in debug mode.

**Comment by mikeaintworkin** [comment]
from the code for get_content() 
in https://github.com/PyGithub/PyGithub/blob/master/github/ProjectCard.py

 **Unfortunately the API doesn't make it clear which you are dealing with.**

```
    # Note that the content_url for any card will be an "issue" URL, from
    # which you can retrieve either an Issue or a PullRequest. Unfortunately
    # the API doesn't make it clear which you are dealing with.
    def get_content(self, content_type=github.GithubObject.NotSet):
        """
        :calls: `GET /repos/{owner}/{repo}/pulls/{number} <https://docs.github.com/en/rest/reference/pulls#get-a-pull-request>`_
        :param content_type: string, optional
        :rtype: :class:`github.PullRequest.PullRequest` or :class:`github.Issue.Issue`
        """
        assert content_type is github.GithubObject.NotSet or isinstance(
            content_type, str
        ), content_type
        if self.content_url is None:
            return None

        if content_type == "PullRequest":
            url = self.content_url.replace("issues", "pulls")
            retclass = github.PullRequest.PullRequest
        elif content_type is github.GithubObject.NotSet or content_type == "Issue":
            url = self.content_url
            retclass = github.Issue.Issue
        else:
            raise ValueError(f"Unknown content type: {content_type}")
        headers, data = self._requester.requestJsonAndCheck("GET", url)
        return retclass(self._requester, headers, data, completed=True)

```

**Comment by mikeaintworkin** [comment]
First thoughts:
- I could force this thing to always try to be a PR?
- I could check the html_url to see and then get the item again?
I'll try that second part first.

**Comment by mikeaintworkin** [comment]
This is just plain a mess.

Here is what you get when the card content indicates that it's a PR but you haven't told the get_content() that you want a PR.



![Image](https://github.com/thisaintwork/iqss_gh_reporting/assets/123129351/2fc77869-092f-4c53-a1c7-94e779c6e09f)

**Comment by mikeaintworkin** [comment]
Here is what you get after you figure out it's a PR and go back and ask it for a PR.

https://api.github.com/repos/IQSS/dataverse/issues/9388
9388 is the number of the PR.
The issue number is actually 9387



In particular, you get the issue_url, but the number is for the PR.
My guess is that the 

![Image](https://github.com/thisaintwork/iqss_gh_reporting/assets/123129351/512965e2-3980-42e7-b0ed-8b1f3f070a4a)

**Comment by mikeaintworkin** [comment]
https://api.github.com/repos/IQSS/dataverse/issues/9387

```
{
  "url": "https://api.github.com/repos/IQSS/dataverse/issues/9387",
  "repository_url": "https://api.github.com/repos/IQSS/dataverse",
  "labels_url": "https://api.github.com/repos/IQSS/dataverse/issues/9387/labels{/name}",
  "comments_url": "https://api.github.com/repos/IQSS/dataverse/issues/9387/comments",
  "events_url": "https://api.github.com/repos/IQSS/dataverse/issues/9387/events",
  "html_url": "https://github.com/IQSS/dataverse/issues/9387",
  "id": 1584881532,
  "node_id": "I_kwDOANZmvM5ed198",
  "number": 9387,
  "title": "Feature Request/Idea: Support protected metadata managed by external applications",
  "user": {
    "login": "qqmyers",
    "id": 6731983,
    "node_id": "MDQ6VXNlcjY3MzE5ODM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/6731983?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/qqmyers",
    "html_url": "https://github.com/qqmyers",
    "followers_url": "https://api.github.com/users/qqmyers/followers",
    "following_url": "https://api.github.com/users/qqmyers/following{/other_user}",
    "gists_url": "https://api.github.com/users/qqmyers/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/qqmyers/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/qqmyers/subscriptions",
    "organizations_url": "https://api.github.com/users/qqmyers/orgs",
    "repos_url": "https://api.github.com/users/qqmyers/repos",
    "events_url": "https://api.github.com/users/qqmyers/events{/privacy}",
    "received_events_url": "https://api.github.com/users/qqmyers/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2023-02-14T21:53:56Z",
  "updated_at": "2023-02-14T21:53:56Z",
  "closed_at": null,
  "author_association": "MEMBER",
  "active_lock_reason": null,
  "body": "**Overview of the Feature Request**\r\nThere are several related use cases in the community for metadata that would be managed by a third-party application, e.g.\r\n- DANS Data Stations where the archiving system wants to store metadata about the archival process/copy in a custom metadata block. The metadata can be shown but edits by humans or other processes would break archiving.\r\n- Workflow (more hypothetical) - where an external workflow system wants to record information about the processing environment and/or how specific files in the dataset are used (input data, output data, etc.), again where changes by humans or other untrusted systems would break things and destroy reproducibility.\r\n\r\n**What existing behavior do you want changed?**\r\n\r\nThe proposed solution is a setting that can associate a metadatablock with a secret key, which has two effects:\r\n\r\n- that block is not shown in the edit metadata display\r\n- all API calls that would allow changes to that block must include a parameter with that key if there are changes being made to that block.\r\n\r\nConcept and proposed implementation have been discussed in Tech Hours. Draft PR to follow.",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/IQSS/dataverse/issues/9387/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/IQSS/dataverse/issues/9387/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
```

**Comment by mikeaintworkin** [comment]
As I read carefully what I'm seeing now is consistent 
The issue_url is just another way of viewing the PR.

So wait? How did I get here? What made me associate issue_url with a list of issues that close a PR.
Where did I make the wrong association/assumption?

If I go this way: I don't get that answer
https://pygithub.readthedocs.io/en/latest/github_objects/ProjectCard.html
	get_content(content_type=NotSet)
		https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest
			issue_url

**Comment by mikeaintworkin** [comment]
Testing the results now.

**Comment by mikeaintworkin** [comment]
FYI: Here is the test loop I used:

make change to create_iq_snapshot in project: iqss_gh_reporting
check them in.
Switch to the "builds" project.
Update it from github
cd ~/DevCode/github-com-mreekie/builds
bash -cl "/usr/bin/python3.10 /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/setup.py bdist_wheel"; pip install .
pushd /home/perftest/DevCode/github-com-mreekie/iqss_gh_reporting/scripts
 ./workflow-May032023sprint-snapshot.sh
create_iq_snapshot
popd
