### ISSUE TITLE
gracefully handle a request to pull back the issue associated with a  PR that does not exist

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/iqss_gh_reporting#41]
Figure out what makes sense to return in the failure case. Make sure to test:
- PR number does not exist
- PR number is an issue number.

**Comment by mikeaintworkin** [comment]
Using: ~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.sh and .py
- ~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/
- export the GITHUB_TOKEN
- ./framework_02.sh
  - The dev code will be built and deployed locally.
  - The shell will submit the test case to the framework_02.py
    - graphql_query_lib.py defines the query 
    - fetch_from_repository has the (sort of) generalized query code and executes the query and returns the results

```
cat<<EOF
--------------------------------
PR does not exist
Issue: Shib group in another group doesn't work #9369
--------------------------------
EOF
python3 framework_02.py \
    --loginOrg "IQSS" \
    --repo "dataverse" \
    --output_dir "${WRK_DIR_RT}/out" \
    --number 9369

cat<<EOF
```

**Comment by mikeaintworkin** [comment]
================================
+ cat
--------------------------------
PR does not exist
search for issue: Shib group in another group doesn't work #9369
--------------------------------
+ python3 framework_02.py --loginOrg IQSS --repo dataverse --output_dir /home/barry/Documents/github_reporting/framework_02/out --number 9369
Running /home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py as the main program
{'query_str': '\n    query ($loginOrg: String!, $repo: String!, $firstFew: Int!, $startWith: String, $number: Int!) {\n        repository(followRenames:false, owner: $loginOrg, name: $repo) {\n                pullRequest (number: $number) {\n                    closingIssuesReferences(first: $firstFew, after: $startWith) {\n                        totalCount\n                        pageInfo {\n                            hasNextPage\n                            hasPreviousPage\n                            endCursor\n                       startCursor\n                        }\n                        nodes {\n                            ...issueFields\n                        }\n\n                    }\n                }\n        }\n    }\n        \n    fragment issueFields on Issue {\n        repository {\n            name\n        }\n        title\n        number\n        id\n        url\n        closed\n        closedAt\n        labels (first: 100) {\n          totalCount\n            nodes {\n                name\n            }\n        }\n    }\n    ', 'has_next_page_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'hasNextPage'], 'start_with_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'endCursor'], 'query_vars': {'loginOrg': 'IQSS', 'repo': 'dataverse', 'number': '', 'firstFew': 100, 'startWith': ''}}
dataverse
Traceback (most recent call last):
File "/home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py", line 62, in <module>
main()
File "/home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py", line 57, in main
fetcher = fetch_from_repository.GraphQLFetcher(auth_token_val, query_dict)
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/iqss_gh_reporting/fetch_from_repository.py", line 37, in __init__
self._fetch_items()
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/iqss_gh_reporting/fetch_from_repository.py", line 54, in _fetch_items
data = client.execute(self._query, variable_values=self._query_input_params)
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/gql/client.py", line 388, in execute
data = loop.run_until_complete(
File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
return future.result()
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/gql/client.py", line 285, in execute_async
return await session.execute(
File "/home/barry/PycharmProjects/iqss_gh_reporting/venv/lib/python3.10/site-packages/gql/client.py", line 1231, in execute
raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'type': 'NOT_FOUND', 'path': ['repository', 'pullRequest'], 'locations': [{'line': 3, 'column': 5}], 'message': 'Could not resolve to a PullRequest with the number of 9369.'}
+ exit 0

**Comment by mikeaintworkin** [comment]
If the item we're looking for is not found, it now returns an empty JSON file defined as: {}

```
-----
kickoff the Test



================================
+ false
+ true
+ cat
--------------------------------
PR does not exist
search for issue: Shib group in another group doesn't work #9369
--------------------------------
+ python3 framework_02.py --loginOrg IQSS --repo dataverse --output_dir /home/barry/Documents/github_reporting/framework_02/out --number 9369
Running /home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py as the main program
{'query_str': '\n    query ($loginOrg: String!, $repo: String!, $firstFew: Int!, $startWith: String, $number: Int!) {\n        repository(followRenames:false, owner: $loginOrg, name: $repo) {\n                pullRequest (number: $number) {\n                    closingIssuesReferences(first: $firstFew, after: $startWith) {\n                        totalCount\n                        pageInfo {\n                            hasNextPage\n                            hasPreviousPage\n                            endCursor\n                       startCursor\n                        }\n                        nodes {\n                            ...issueFields\n                        }\n\n                    }\n                }\n        }\n    }\n        \n    fragment issueFields on Issue {\n        repository {\n            name\n        }\n        title\n        number\n        id\n        url\n        closed\n        closedAt\n        labels (first: 100) {\n          totalCount\n            nodes {\n                name\n            }\n        }\n    }\n    ', 'has_next_page_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'hasNextPage'], 'start_with_path': ['repository', 'pullRequest', 'closingIssuesReferences', 'pageInfo', 'endCursor'], 'query_vars': {'loginOrg': 'IQSS', 'repo': 'dataverse', 'number': '', 'firstFew': 100, 'startWith': ''}}
dataverse
Transport error: {'type': 'NOT_FOUND', 'path': ['repository', 'pullRequest'], 'locations': [{'line': 3, 'column': 5}], 'message': 'Could not resolve to a PullRequest with the number of 9369.'}
Saving result to file:
/home/barry/Documents/github_reporting/framework_02/out/output.json
+ false
+ false
barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding$ ^C
barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/scripts/scaffolding$ cat /home/barry/Documents/github_reporting/framework_02/out/output.json
{}

```

**Comment by mikeaintworkin** [comment]
The second case - the number queried for is not a PR or an Issue, it just doesn't exist.

```
-----
kickoff the Test



================================
--------------------------------
PR does not exist
#9999
--------------------------------
Running /home/barry/PycharmProjects/iqss_gh_reporting/scripts/scaffolding/framework_02.py as the main program
Query dictionary
----
{
"query_str": "\n    query ($loginOrg: String!, $repo: String!, $firstFew: Int!, $startWith: String, $number: Int!) {\n        repository(followRenames:false, owner: $loginOrg, name: $repo) {\n                pullRequest (number: $number) {\n                    closingIssuesReferences(first: $firstFew, after: $startWith) {\n                        totalCount\n                        pageInfo {\n                            hasNextPage\n                            hasPreviousPage\n                            endCursor\n                    startCursor\n                        }\n                        nodes {\n                            ...issueFields\n                        }\n\n                    }\n                }\n        }\n    }\n        \n    fragment issueFields on Issue {\n        repository {\n            name\n        }\n        title\n        number\n        id\n        url\n        closed\n        closedAt\n        labels (first: 100) {\n          totalCount\n            nodes {\n                name\n            }\n        }\n    }\n    ",
"has_next_page_path": [
"repository",
"pullRequest",
"closingIssuesReferences",
"pageInfo",
"hasNextPage"
],
"start_with_path": [
"repository",
"pullRequest",
"closingIssuesReferences",
"pageInfo",
"endCursor"
],
"query_vars": {
"loginOrg": "IQSS",
"firstFew": 100,
"repo": "dataverse",
"number": 9999
}
}
----

Transport error: {'type': 'NOT_FOUND', 'path': ['repository', 'pullRequest'], 'locations': [{'line': 3, 'column': 5}], 'message': 'Could not resolve to a PullRequest with the number of 9999.'}
results:
---- 
{}
----

Saving result to file:
/home/barry/Documents/github_reporting/framework_02/out/output.json
```
