### ISSUE TITLE
Return all the open issues from a single repository. Include what projects each issue belongs to.

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/iqss_gh_reporting#60]
Return all the open issues from a single repository. Include what projects each issue belongs to.

I want to collect all of the issues related to working on sid that:
- Are not operations related
- Are open
- Are not part of hmdc-DevOpsProjects

I only have the DevOpsProjects repo to deal with.

So I'm thinking as the overall process
- Dump all issues, all fields, from DevOpsProjects repo
- import it into a sheet
- get a list of the issue numbers I care about
- add each issue I care about into the project I'm going to use to review them.

context:
- I'm returning from a long absence again.
- I probably should be using what Ceilyn has created, but I don't want to be fumbling around and possibly checking in bugs. I'd rather muddy my own pond.

**Comment by mikeaintworkin** [comment]
Copied framework_05.sh as framework_07.sh

**Comment by mikeaintworkin** [comment]
OK. So I got the basics going. I was able to build and deploy the software locally using framework_07.sh
That's all that does.
Now I'm going to look at workflow run_a gql_query  and see if that is working and if I can get that to run the query I want.

**Comment by mikeaintworkin** [comment]
barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/build_test/build_test_scripts$ run_a_gql_query
Running /home/barry/.local/bin/run_a_gql_query as the main program
Traceback (most recent call last):
File "/home/barry/.local/bin/run_a_gql_query", line 53, in <module>
main()
File "/home/barry/.local/bin/run_a_gql_query", line 32, in main
raise ValueError(f"Error: there must be a valid input.yaml file in the current working dir: {os.getcwd()}")
ValueError: Error: there must be a valid input.yaml file in the current working dir: /home/barry/PycharmProjects/iqss_gh_reporting/build_test/build_test_scripts
barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/build_test/build_test_scripts$

**Comment by mikeaintworkin** [comment]
Ok so I'm caught up now.
This code is still a work in progress.
I just removed the requirement or a yaml file.
I should have enough with just the token.

Creating a token that will work with our repository now.

**Comment by mikeaintworkin** [comment]
In graph_query_lib.py I'm running with the defaults so I updated the code.

def query_get_project_basics(login_org: str = "hmdc", project_num: int = 33):

and... Success!

```
barry@ubuntux64-20230604:~/PycharmProjects/iqss_gh_reporting/build_test/build_test_scripts$ run_a_gql_query
results:
----
{
"organization": {
"projectV2": {
"title": "\ud83d\udcc4<Req> Sid Feature Requests Backlog",
"url": "https://github.com/orgs/hmdc/projects/33"
}
}
}
----
```

**Comment by mikeaintworkin** [comment]
Next step:
 - Keep using the defaults in the code for now.
 - switch to a query on the repo. "def query_get_all_issues():"
 - once that's running, add a query based on that one that includes the project information

That should do it for what I need right now.

**Comment by mikeaintworkin** [comment]
I've been reconstructing the graphql query from scratch to get myself back into the flow for graphql.
I've reached this point before having to kick off for now

```
         query ($loginOrg: String!, $repo: String!, $firstFew: Int, $startWith: String) {
            repository(followRenames:false, owner: $loginOrg, name: $repo) {
                id
                name
                url
                owner {
                    login
                }
                issues(first: $firstFew, after: $startWith) {
                    # IssueConnection properties
                    totalCount
                    pageInfo
                    # PageInfo properties
                    {
                        hasNextPage
                        hasPreviousPage
                        endCursor
                        startCursor
                    }
                    # list of Nodes of type issue
                    nodes
                    {
                        
                    # Issue has a projects V2 object.
                    # I can assume that I only need the first 2 or three to get all, so first 100 is safe     
                    ProjectsV2(first: $firstFew)
                    }

                }
            }
        }
```

**Comment by mikeaintworkin** [comment]
It took all day between meetings, but I've got it!!!
Tomorrow I'll be able to dump the list and get those into the right project.
